name: Publish to NPM

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          scope: '@qlexqndru'

      - name: Enable Yarn
        run: corepack enable

      - name: Install Dependencies
        run: |
          rm -rf dist/
          yarn install --no-immutable

      - name: Build
        run: yarn build

      - name: Verify Package
        run: |
          echo "Checking package.json name"
          cat package.json | grep name
          echo "Checking package contents"
          npm pack --dry-run
          echo "Checking dist directory"
          ls -la dist/

      - name: Publish Release
        if: ${{ github.event.release.prerelease == false }}
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          npm publish --access public --scope=@qlexqndru
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}