name: Publish Beta to NPM

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          scope: '@qlexqndru'

      - name: Install Dependencies
        run: |
          rm -f yarn.lock
          rm -rf dist/
          yarn install --force

      - name: Build
        run: yarn build

      - name: Verify Package
        run: |
          echo "Checking package.json name"
          cat package.json | grep name
          echo "Checking dist directory"
          ls -la dist/

      - name: Publish
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}