name: storybook

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Enable Yarn
        run: corepack enable

      - name: Install and Build
        run: |
          yarn install --no-immutable
          yarn run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: storybook-static
          folder: storybook-static